<?php

return array(
	'callouts' => array(
		'label' => __( 'Callout Text', 'crazy-pills' ),
		'grid' => array( 1, 4 ),
		'def' => array(
			array( 'text' => __( 'Alert', 'crazy-pills' ),   'value' => 'alert',   'color' => 'orange' ),
			array( 'text' => __( 'Error', 'crazy-pills' ),   'value' => 'error',   'color' => 'red' ),
			array( 'text' => __( 'Success', 'crazy-pills' ), 'value' => 'success', 'color' => 'green' ),
			array( 'text' => __( 'Info', 'crazy-pills' ),    'value' => 'info',    'color' => 'blue' ),
		),
		'template' => '<div class="cp_%value%">%text%</div>',
		'default_text' => __( 'Message box contents...', 'crazy-pills' ),
	),
	'highlights' => array(
		'label' => __( 'Highlight Text', 'crazy-pills' ),
		'grid' => array( 3, 4 ),
		'def' => array(
			array( 'text' => __( 'Yellow', 'crazy-pills' ),  'value' => 'yellow',  'color' => 'yellow' ),
			array( 'text' => __( 'Brown', 'crazy-pills' ),   'value' => 'brown',   'color' => 'brown' ),
			array( 'text' => __( 'Black', 'crazy-pills' ),   'value' => 'black',   'color' => 'black' ),
			array( 'text' => __( 'Blue', 'crazy-pills' ),    'value' => 'blue',    'color' => 'blue' ),
			array( 'text' => __( 'Green', 'crazy-pills' ),   'value' => 'green',   'color' => 'green' ),
			array( 'text' => __( 'Silver', 'crazy-pills' ),  'value' => 'silver',  'color' => 'silver' ),
			array( 'text' => __( 'Magenta', 'crazy-pills' ), 'value' => 'magenta', 'color' => 'magenta' ),
			array( 'text' => __( 'Natural', 'crazy-pills' ), 'value' => 'natural', 'color' => 'natural' ),
			array( 'text' => __( 'Orange', 'crazy-pills' ),  'value' => 'orange',  'color' => 'orange' ),
			array( 'text' => __( 'Purple', 'crazy-pills' ),  'value' => 'purple',  'color' => 'purple' ),
			array( 'text' => __( 'Red', 'crazy-pills' ),     'value' => 'red',     'color' => 'red' ),
			array( 'text' => __( 'Teal', 'crazy-pills' ),    'value' => 'teal',    'color' => 'teal' ),
		),
		'template' => '<span class="cp_highlight %value%">%text%</span>&nbsp;',
		'default_text' => __( 'Highlighted text...', 'crazy-pills' ),
	),
	'buttons' => array(
		'label' => __( 'Button', 'crazy-pills' ),
		'grid' => array( 2, 4 ),
		'def' => array(
			array( 'text' => __( 'Light Blue', 'crazy-pills' ), 'value' => 'light-blue', 'color' => 'lightblue' ),
			array( 'text' => __( 'Blue', 'crazy-pills' ),       'value' => 'blue',       'color' => 'blue' ),
			array( 'text' => __( 'Green', 'crazy-pills' ),      'value' => 'green',      'color' => 'green' ),
			array( 'text' => __( 'Red', 'crazy-pills' ),        'value' => 'red',        'color' => 'red' ),
			array( 'text' => __( 'Orange', 'crazy-pills' ),     'value' => 'orange',     'color' => 'orange' ),
			array( 'text' => __( 'Purple', 'crazy-pills' ),     'value' => 'purple',     'color' => 'purple' ),
			array( 'text' => __( 'Gray', 'crazy-pills' ),       'value' => 'grey',       'color' => 'gray' ),
			array( 'text' => __( 'Black', 'crazy-pills' ),      'value' => 'black',      'color' => 'black' ),
		),
		'template' => '<a href="#" class="cp_button %value%">%text%</a>',
		'default_text' => __( 'Button', 'crazy-pills' ),
	),
	'checks' => array(
		'label' => __( 'Check List', 'crazy-pills' ),
		'grid' => array( 3, 3 ),
		'def' => array(
			array( 'text' => __( 'Green', 'crazy-pills' ),     'value' => 'green',    'color' => 'green' ),
			array( 'text' => __( 'Blue', 'crazy-pills' ),      'value' => 'blue',     'color' => 'blue' ),
			array( 'text' => __( 'Dark Blue', 'crazy-pills' ), 'value' => 'darkblue', 'color' => 'darkblue' ),
			array( 'text' => __( 'Gray', 'crazy-pills' ),      'value' => 'gray',     'color' => 'gray' ),
			array( 'text' => __( 'Orange', 'crazy-pills' ),    'value' => 'orange',   'color' => 'orange' ),
			array( 'text' => __( 'Pink', 'crazy-pills' ),      'value' => 'pink',     'color' => 'pink' ),
			array( 'text' => __( 'Purple', 'crazy-pills' ),    'value' => 'purple',   'color' => 'purple' ),
			array( 'text' => __( 'Red', 'crazy-pills' ),       'value' => 'red',      'color' => 'red' ),
			array( 'text' => __( 'Black', 'crazy-pills' ),     'value' => 'black',    'color' => 'black' ),
		),
		'template' => '<ul class="cp_check %value%"><li>%text%</li></ul>',
		'default_text' => __( 'List item', 'crazy-pills' ),
	),
	'bullets' => array(
		'label' => __( 'Bullet List', 'crazy-pills' ),
		'grid' => array( 2, 4 ),
		'def' => array(
			array( 'text' => __( 'Green', 'crazy-pills' ),  'value' => 'green',  'color' => 'green' ),
			array( 'text' => __( 'Blue', 'crazy-pills' ),   'value' => 'blue',   'color' => 'blue' ),
			array( 'text' => __( 'Orange', 'crazy-pills' ), 'value' => 'orange', 'color' => 'orange' ),
			array( 'text' => __( 'Pink', 'crazy-pills' ),   'value' => 'pink',   'color' => 'pink' ),
			array( 'text' => __( 'Purple', 'crazy-pills' ), 'value' => 'purple', 'color' => 'purple' ),
			array( 'text' => __( 'Yellow', 'crazy-pills' ), 'value' => 'yellow', 'color' => 'yellow' ),
			array( 'text' => __( 'Red', 'crazy-pills' ),    'value' => 'red',    'color' => 'red' ),
			array( 'text' => __( 'Black', 'crazy-pills' ),  'value' => 'black',  'color' => 'black' ),
		),
		'template' => '<ul class="cp_bullet %value%"><li>%text%</li></ul>',
		'default_text' => __( 'List item', 'crazy-pills' ),
	),
);